# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: catalog
    password:
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
        - USER

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NzZmMzgzZDMzNmIyMDIwOGZiYzM0NmUyNDRjN2UyODljZTZlZWVkNjM4YTU3YTQxNmI1ZmE0YjM2YmRmNjQ4ODc1Y2Q2ZmI2NWUyYmZlZmVmYzg3YmU4MDEwZDIzZjczZjdjNzBjY2E5ZTM2ODg0ODA1NjgxZDIyMjUyOWIxMjg=
