package ar.edu.um.turnos.catalog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalCategoryAllPropertiesEquals(ProfessionalCategory expected, ProfessionalCategory actual) {
        assertProfessionalCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalCategoryAllUpdatablePropertiesEquals(ProfessionalCategory expected, ProfessionalCategory actual) {
        assertProfessionalCategoryUpdatableFieldsEquals(expected, actual);
        assertProfessionalCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalCategoryAutoGeneratedPropertiesEquals(ProfessionalCategory expected, ProfessionalCategory actual) {
        assertThat(actual)
            .as("Verify ProfessionalCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalCategoryUpdatableFieldsEquals(ProfessionalCategory expected, ProfessionalCategory actual) {
        assertThat(actual)
            .as("Verify ProfessionalCategory relevant properties")
            .satisfies(a -> assertThat(a.getExternalId()).as("check externalId").isEqualTo(expected.getExternalId()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getEnabled()).as("check enabled").isEqualTo(expected.getEnabled()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalCategoryUpdatableRelationshipsEquals(ProfessionalCategory expected, ProfessionalCategory actual) {
        // empty method
    }
}
