package ar.edu.um.turnos.catalog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WeeklyScheduleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeeklyScheduleAllPropertiesEquals(WeeklySchedule expected, WeeklySchedule actual) {
        assertWeeklyScheduleAutoGeneratedPropertiesEquals(expected, actual);
        assertWeeklyScheduleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeeklyScheduleAllUpdatablePropertiesEquals(WeeklySchedule expected, WeeklySchedule actual) {
        assertWeeklyScheduleUpdatableFieldsEquals(expected, actual);
        assertWeeklyScheduleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeeklyScheduleAutoGeneratedPropertiesEquals(WeeklySchedule expected, WeeklySchedule actual) {
        assertThat(actual)
            .as("Verify WeeklySchedule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeeklyScheduleUpdatableFieldsEquals(WeeklySchedule expected, WeeklySchedule actual) {
        assertThat(actual)
            .as("Verify WeeklySchedule relevant properties")
            .satisfies(a -> assertThat(a.getExternalId()).as("check externalId").isEqualTo(expected.getExternalId()))
            .satisfies(a -> assertThat(a.getDayOfWeek()).as("check dayOfWeek").isEqualTo(expected.getDayOfWeek()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()))
            .satisfies(a ->
                assertThat(a.getSlotDurationMinutes()).as("check slotDurationMinutes").isEqualTo(expected.getSlotDurationMinutes())
            )
            .satisfies(a -> assertThat(a.getEnabled()).as("check enabled").isEqualTo(expected.getEnabled()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeeklyScheduleUpdatableRelationshipsEquals(WeeklySchedule expected, WeeklySchedule actual) {
        assertThat(actual)
            .as("Verify WeeklySchedule relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
